### ISSUE TITLE
rust lsp crash

### ISSUE THREAD

**Issue by nanakura** [jadestrong/lsp-copilot#1]
![image](https://github.com/user-attachments/assets/43391a49-53d5-4424-b35e-12e49280dc4f)
![image](https://github.com/user-attachments/assets/20baf362-f46e-486d-b014-c8ee31bc06d0)

**Comment by jadestrong** [comment]
`auto-format` 字段是你自己配置的吗？

**Comment by nanakura** [comment]
> `auto-format` 字段是你自己配置的吗？

我使用doom，参照README进行配置，没有额外配置

**Comment by nanakura** [comment]
> `auto-format` 字段是你自己配置的吗？

![image](https://github.com/user-attachments/assets/80f19ae2-4b3a-4db0-9d3c-0afefdb1e5e5)
是因为这个引起的？

**Comment by nanakura** [comment]
> > `auto-format` 字段是你自己配置的吗？
> 
> ![image](https://private-user-images.githubusercontent.com/69560752/386917940-80f19ae2-4b3a-4db0-9d3c-0afefdb1e5e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MTUyMjksIm5iZiI6MTczMTgxNDkyOSwicGF0aCI6Ii82OTU2MDc1Mi8zODY5MTc5NDAtODBmMTlhZTItNGIzYS00ZGIwLTlkM2MtMGFmZWZkYjFlNWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDAzNDIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MmJkYzlkNDMwMDYwYWEzMmE4YmU4NDRhMTA1Y2NkZTY0Y2ZiM2QwMjRkYmJkMDg4YjE3MTYwZmZjZWNhOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wjBwGXUkJeXnPyVD8bY04Bu3QUdZSqexFK_Vvm2tP2A) 是因为这个引起的？

试了下把这个关了也没啥用

**Comment by nanakura** [comment]
我改了config没删干净。。。。
