### ISSUE TITLE
gopls completion not work

### ISSUE THREAD

**Issue by nanakura** [jadestrong/lsp-copilot#2]
参照 https://github.com/helix-editor/helix/blob/master/languages.toml 进行了如下配置
![image](https://github.com/user-attachments/assets/d75aa773-f3dc-49ce-83cc-e80ae65e676d)
但是补全未生效，minibuffer没有报错信息
lsp copilot events如下
![image](https://github.com/user-attachments/assets/753b6f08-9274-48a0-841f-805091dd2127)
log如下
![image](https://github.com/user-attachments/assets/508bd90b-7347-4c11-aa02-d4081e989c09)

**Comment by jadestrong** [comment]
看着好像没报错，goto definition 功能能用吗？

**Comment by nanakura** [comment]
> 看着好像没报错，goto definition 功能能用吗？

阿哲，执行`lsp-copilot-find-declaration`说没有lsp
![image](https://github.com/user-attachments/assets/63b175fe-c04a-4246-b7c7-98b42d6c891d)

**Comment by jadestrong** [comment]
是加在了 `M-x lsp-copilot-open-config-file` 里的不？看起来配置没问题

**Comment by jadestrong** [comment]
![image](https://github.com/user-attachments/assets/f6f791d2-4bfb-47f1-af5e-4254e6a39f1a)
如果上面都没问题，可以看看 rust 服务的log文件里有没有报错信息

**Comment by nanakura** [comment]
> ![image](https://private-user-images.githubusercontent.com/18475217/386920448-f6f791d2-4bfb-47f1-af5e-4254e6a39f1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MTkxNDgsIm5iZiI6MTczMTgxODg0OCwicGF0aCI6Ii8xODQ3NTIxNy8zODY5MjA0NDgtZjZmNzkxZDItNGJmYi00N2YxLWFmNWUtNDI1NGU2YTM5ZjFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA0NDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2OWNkMjgwYzAxMTVmYWIyMzE3M2M1Y2FmZDJhMGVkZjQ4YjI0YWY0M2IyYzExYTU0ZGY0NTY0MTM5NjViZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9C2pE4S08SykrjJL737n_CbVdd1yxBw5lBLVm7zLEJk) 如果上面都没问题，可以看看 rust 服务的log文件里有没有报错信息

是使用M-x lap-copilot-open-config-file配置的，rust的运行状况良好，只有配置的go有问题

**Comment by nanakura** [comment]
> 加了配置之后 restart 了没，或者 gopls 命令终端上是可以访问的是么？

restart过了,gopls在PATH里

**Comment by nanakura** [comment]
> ![image](https://private-user-images.githubusercontent.com/18475217/386929143-4d9dd849-5bc2-46e6-b20b-20c3ef97c200.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4Mjg5ODUsIm5iZiI6MTczMTgyODY4NSwicGF0aCI6Ii8xODQ3NTIxNy8zODY5MjkxNDMtNGQ5ZGQ4NDktNWJjMi00NmU2LWIyMGItMjBjM2VmOTdjMjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3MzEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNWY2MjZhMTdiY2UxNDBkYjBiYjc2NWZlNTEzNjE4MzBlM2IzZGIxNGVjNjFkMDI0ZmYzYzg1NjE4OGRjOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rwahNTkS6ev2n0SldYYPB0WO7P6D9YveYSyLYhYtmtU) ![image](https://private-user-images.githubusercontent.com/18475217/386929698-dbf23a2a-beed-4b57-854e-bc33002775d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4Mjg5ODUsIm5iZiI6MTczMTgyODY4NSwicGF0aCI6Ii8xODQ3NTIxNy8zODY5Mjk2OTgtZGJmMjNhMmEtYmVlZC00YjU3LTg1NGUtYmMzMzAwMjc3NWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3MzEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MDYzODliMzkzMzIwY2Y0MDUyNjgzYmU2NjUwN2M0ZTFhYjg0MjI0ZmMwMGI0OThlYjRmNDIwZWIwYzZkM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rcZHleiZ0r8Q15YSdhQsi_hJdGICcgEdRD-nmhqoQZM) ![image](https://private-user-images.githubusercontent.com/18475217/386929409-7b6b0d2c-e7cd-43fa-a390-516feba51579.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4Mjg5ODUsIm5iZiI6MTczMTgyODY4NSwicGF0aCI6Ii8xODQ3NTIxNy8zODY5Mjk0MDktN2I2YjBkMmMtZTdjZC00M2ZhLWEzOTAtNTE2ZmViYTUxNTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3MzEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MWMwMDhmNjRhZmIzYjRlZWUyMTFjY2ZkYmJkNGMzMmQwYjc1Y2MyNWJkNjI1YWVmMzliMDQ5NWZkOTg4NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HvH-jTASzZD3pN6MdJK2zjv7LFTtmi1Pfnwxq7syAgo)
> 
> 我在虚拟机里试了下是可以的, 只要 gopls 确实能访问到才行 ![image](https://private-user-images.githubusercontent.com/18475217/386929918-f1c39f12-055a-4a5c-98b1-fe31aef241cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4Mjg5ODUsIm5iZiI6MTczMTgyODY4NSwicGF0aCI6Ii8xODQ3NTIxNy8zODY5Mjk5MTgtZjFjMzlmMTItMDU1YS00YTVjLTk4YjEtZmUzMWFlZjI0MWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3MzEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZTczZWVhZmI3NDdjOWExMGE4ZGNjM2JjZjhhOTdmMDlmNzhlZTY1NTU3ZGUxM2QxNjYyMjAxNjBkMTY5OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3DplMBwx0zv1UreXKawCR_NupJUysGpI8-wV3iWyiIU)

我尝试拉取了新的分支，然后出现了新的报错，是不是这个引起的
![image](https://github.com/user-attachments/assets/2181e2a1-0290-403f-9b02-bdca413f95f4)

**Comment by nanakura** [comment]
> > ![image](https://private-user-images.githubusercontent.com/18475217/386929143-4d9dd849-5bc2-46e6-b20b-20c3ef97c200.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4Mjg5ODUsIm5iZiI6MTczMTgyODY4NSwicGF0aCI6Ii8xODQ3NTIxNy8zODY5MjkxNDMtNGQ5ZGQ4NDktNWJjMi00NmU2LWIyMGItMjBjM2VmOTdjMjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3MzEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNWY2MjZhMTdiY2UxNDBkYjBiYjc2NWZlNTEzNjE4MzBlM2IzZGIxNGVjNjFkMDI0ZmYzYzg1NjE4OGRjOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rwahNTkS6ev2n0SldYYPB0WO7P6D9YveYSyLYhYtmtU) ![image](https://private-user-images.githubusercontent.com/18475217/386929698-dbf23a2a-beed-4b57-854e-bc33002775d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4Mjg5ODUsIm5iZiI6MTczMTgyODY4NSwicGF0aCI6Ii8xODQ3NTIxNy8zODY5Mjk2OTgtZGJmMjNhMmEtYmVlZC00YjU3LTg1NGUtYmMzMzAwMjc3NWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3MzEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MDYzODliMzkzMzIwY2Y0MDUyNjgzYmU2NjUwN2M0ZTFhYjg0MjI0ZmMwMGI0OThlYjRmNDIwZWIwYzZkM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rcZHleiZ0r8Q15YSdhQsi_hJdGICcgEdRD-nmhqoQZM) ![image](https://private-user-images.githubusercontent.com/18475217/386929409-7b6b0d2c-e7cd-43fa-a390-516feba51579.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4Mjg5ODUsIm5iZiI6MTczMTgyODY4NSwicGF0aCI6Ii8xODQ3NTIxNy8zODY5Mjk0MDktN2I2YjBkMmMtZTdjZC00M2ZhLWEzOTAtNTE2ZmViYTUxNTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3MzEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MWMwMDhmNjRhZmIzYjRlZWUyMTFjY2ZkYmJkNGMzMmQwYjc1Y2MyNWJkNjI1YWVmMzliMDQ5NWZkOTg4NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HvH-jTASzZD3pN6MdJK2zjv7LFTtmi1Pfnwxq7syAgo)
> > 我在虚拟机里试了下是可以的, 只要 gopls 确实能访问到才行 ![image](https://private-user-images.githubusercontent.com/18475217/386929918-f1c39f12-055a-4a5c-98b1-fe31aef241cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4Mjg5ODUsIm5iZiI6MTczMTgyODY4NSwicGF0aCI6Ii8xODQ3NTIxNy8zODY5Mjk5MTgtZjFjMzlmMTItMDU1YS00YTVjLTk4YjEtZmUzMWFlZjI0MWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3MzEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZTczZWVhZmI3NDdjOWExMGE4ZGNjM2JjZjhhOTdmMDlmNzhlZTY1NTU3ZGUxM2QxNjYyMjAxNjBkMTY5OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3DplMBwx0zv1UreXKawCR_NupJUysGpI8-wV3iWyiIU)
> 
> 我尝试拉取了新的分支，然后出现了新的报错，是不是这个引起的 ![image](https://private-user-images.githubusercontent.com/69560752/386930240-2181e2a1-0290-403f-9b02-bdca413f95f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MjkzMjYsIm5iZiI6MTczMTgyOTAyNiwicGF0aCI6Ii82OTU2MDc1Mi8zODY5MzAyNDAtMjE4MWUyYTEtMDI5MC00MDNmLTliMDItYmRjYTQxM2Y5NWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA3MzcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYTAyNWZkMDAyZGE2NGFmN2RlOWU4ZWNiY2IyYTdkMmM5ZThlYzRkMjU5ODQ0ZWQxYzY1MTAxMDA2MjQ2YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x6bMGRIFsYoLzcOP-9-2OoknPQEpa_a6nagrcU_KbjI)

好吧，vfork的错是重装lsp-copilot他没有进行prebuild造成的
但是我确信我的gopls在PATH里
![image](https://github.com/user-attachments/assets/99fd1c7f-c7a7-4493-a72e-6674cdb91d61)
以及配置文件是使用`M-x lsp-copilot-open-config-file`打开的
![image](https://github.com/user-attachments/assets/e6185bbd-d3e2-4979-9653-ac22c18aa53c)

**Comment by jadestrong** [comment]
你看下 lsp-copilot-open-log-file 里面正常吗，有没有补全请求发送？

**Comment by nanakura** [comment]
> 你看下 lsp-copilot-open-log-file 里面正常吗，有没有补全请求发送？

![image](https://github.com/user-attachments/assets/0f28f4d3-090e-4f6b-8be9-1b6c038759ed)
只显示了启动

**Comment by jadestrong** [comment]
你去 go 文件里编辑一下看看这里的日志是什么

**Comment by jadestrong** [comment]
`find-delcare` 命令是会提示 no Sever ，我回头看看，这个命令我很少用，但是 find-definition 应该是可以的，另外，如果不提示，你得看下 company-bankends 第一个是不是 company-capf （如果是用的 company 的话）

**Comment by nanakura** [comment]
> `find-delcare` 命令是会提示 no Sever ，我回头看看，这个命令我很少用，但是 find-definition 应该是可以的，另外，如果不提示，你得看下 company-bankends 第一个是不是 company-capf （如果是用的 company 的话）

似乎就是这个的问题，手动`M-x company-capf`是有效果的，但是我已经设置了`(setq +lsp-company-backends '(company-capf company-yasnippet company-dabbrev company-dabbrev-code))`

**Comment by nanakura** [comment]
> > `find-delcare` 命令是会提示 no Sever ，我回头看看，这个命令我很少用，但是 find-definition 应该是可以的，另外，如果不提示，你得看下 company-bankends 第一个是不是 company-capf （如果是用的 company 的话）
> 
> 似乎就是这个的问题，手动`M-x company-capf`是有效果的，但是我已经设置了`(setq +lsp-company-backends '(company-capf company-yasnippet company-dabbrev company-dabbrev-code))`

虽然不知道为什么company-capf失效，但是换成corfu就没事了

**Comment by jadestrong** [comment]
应该是 doom-emacs 里面有地方 set-company-backend 之类的，我在测试 vue 的时候也遇到了：
```
      +lsp-company-backends '(company-capf :separate company-dabbrev)
      +company-backend-alist '((text-mode (:separate company-dabbrev company-yasnippet))
                               (web-mode (company-capf :separate company-dabbrev))
                               (prog-mode (company-capf :separate company-dabbrev)) 
                               (conf-mode company-capf company-dabbrev-code company-yasnippet))
```
我之前都是这么配置的，只在 vue 哪里失效了

**Comment by nanakura** [comment]
> 应该是 doom-emacs 里面有地方 set-company-backend 之类的，我在测试 vue 的时候也遇到了：
> 
> ```
>       +lsp-company-backends '(company-capf :separate company-dabbrev)
>       +company-backend-alist '((text-mode (:separate company-dabbrev company-yasnippet))
>                                (web-mode (company-capf :separate company-dabbrev))
>                                (prog-mode (company-capf :separate company-dabbrev)) 
>                                (conf-mode company-capf company-dabbrev-code company-yasnippet))
> ```
> 
> 我之前都是这么配置的，只在 vue 哪里失效了

似乎是doom的xxx-mode会自动覆盖company-backend: https://github.com/doomemacs/doomemacs/issues/6261
根据这个issue得手动在xxx-mode设置backend
```elisp
(after! go-mode
  (add-hook 'before-save-hook 'gofmt-before-save)
  (setq tab-width 2)
  (setq gofmt-command "goimports")
  (setq standard-indent 2)
  (setq indent-tabs-mode nil)
  (set-company-backend! 'go-mode '(company-capf :separate company-dabbrev))
)
```
