### ISSUE TITLE
Custom configuration path

### ISSUE THREAD

**Issue by nanakura** [jadestrong/lsp-copilot#3]
lsp的toml配置路径默认在`~/.config/emacs/.local/cache`下，不是很方便同步到`dotfiles`里，能不能指定配置的路径，比如放到doom配置的文件夹里

**Comment by jadestrong** [comment]
你自己自定义下这个 `lsp-copilot-user-languages-config` 变量应该就可以

**Comment by jadestrong** [comment]
比如这样： `(setq lsp-copilot-user-languages-config (expand-file-name (concat doom-user-dir (file-name-as-directory "lsp-copilot") "languages.toml")))`
