### ISSUE TITLE
有考虑做 wilki 吗

### ISSUE THREAD

**Issue by nesteiner** [jadestrong/lsp-copilot#5]
你好，这个项目很不错，我想学习下这个项目
我想问下有没有做wiki的打算，我想学习
1. 这个包的第三方库的作用
2. 这个项目的组织形式
3. 这个项目的核心思路
4. 如何用自己的思路重新写一遍这个项目
5. 他如何调用其他 lsp-server

顺带给你个 star 🙂

**Comment by jadestrong** [comment]
OK 我后面有空的时候整理下，写写架构设计和工作方式
