### ISSUE TITLE
会导致tabnine等第三方补全失效

### ISSUE THREAD

**Issue by TheEros** [jadestrong/lsp-copilot#8]

**Comment by jadestrong** [comment]
补全配置是怎么配置的？

**Comment by TheEros** [comment]
![image](https://github.com/user-attachments/assets/4faea6f8-3910-4f8d-86dd-e67208f3549d)
这是tabninie没添加lsp_copilot的时候可以使用的配置

**Comment by jadestrong** [comment]
[fix/tabnine](https://github.com/jadestrong/lsp-copilot/tree/fix/tabnine) 试下这个分支是不是可以？

**Comment by jadestrong** [comment]
再拉一下这个分支最新代码试试呢，注册 lsp-copilot-completion-at-point 的方式和lsp-mode对齐了

**Comment by TheEros** [comment]
能看到tabinie启动了 但是补全菜单里依旧没有

**Comment by jadestrong** [comment]
那我安装下试试看把

**Comment by jadestrong** [comment]
你看下当前buffer的 `completion-at-point-functions` 变量的值是什么？

**Comment by TheEros** [comment]
![Uploading image.png…]()

**Comment by TheEros** [comment]
![image](https://github.com/user-attachments/assets/da5e0466-c843-426f-b3e4-03d6e49c3ff1)

**Comment by TheEros** [comment]
> > 能看到tabinie启动了 但是补全菜单里依旧没有
> 
> 那现在是补全菜单里没有lsp的内容还是没有 tabnine 的内容，看起来 tabnine 在前面，另外，你可以把 cape-file 里的 lsp-completion-at-point 换成 lsp-copilot-completion-at-point

换成 lsp-copilot-completion-at-point可以了

**Comment by TheEros** [comment]
有办法把tabnine的补全放到补全菜单的第三或者第四行么

**Comment by jadestrong** [comment]
照着论坛里的写法模仿着写了一下这个，不过我没用 corfu 不清楚有没有问题：
```
(when (fboundp #'tabnine-completion-at-point)
  (add-hook 'lsp-copilot-mode-hook
            (defun lsp-copilot-capf ()
              (remove-hook 'completion-at-point-functions #'lsp-copilot-completion-at-point t)
              (add-hook 'completion-at-point-functions
                        (cape-capf-super
                         #'lsp-copilot-completion-at-point
                         #'tabnine-completion-at-point) nil t))))

```

**Comment by jadestrong** [comment]
> 有办法把tabnine的补全放到补全菜单的第三或者第四行么

原来的 lsp-mode 是可以的吗？有可能是 lsp-mode 是在 emacs 端做了排序所以支持在前面，lsp-copilot 是在服务端做的排序，我再看看有没有方法做到

**Comment by TheEros** [comment]
> > 有办法把tabnine的补全放到补全菜单的第三或者第四行么
> 
> 原来的 lsp-mode 是可以的吗？有可能是 lsp-mode 是在 emacs 端做了排序所以支持在前面，lsp-copilot 是在服务端做的排序，我再看看有没有方法做到

原来不会一致出现在最后，应该是在emacs端做了排序

**Comment by jadestrong** [comment]
![image](https://github.com/user-attachments/assets/20d774fe-e92b-4bbd-adbc-d0610efa9634)
我看按下面这么配上就可以排序了， tabnine 里面好像一块进行排序了

> 照着论坛里的写法模仿着写了一下这个，不过我没用 corfu 不清楚有没有问题：
> 
> ```
> (when (fboundp #'tabnine-completion-at-point)
>   (add-hook 'lsp-copilot-mode-hook
>             (defun lsp-copilot-capf ()
>               (remove-hook 'completion-at-point-functions #'lsp-copilot-completion-at-point t)
>               (add-hook 'completion-at-point-functions
>                         (cape-capf-super
>                          #'lsp-copilot-completion-at-point
>                          #'tabnine-completion-at-point) nil t))))
> ```

**Comment by TheEros** [comment]
![image](https://github.com/user-attachments/assets/5d0ea5b4-0a82-4a07-9ddd-dbf4b9c458e1)
我这里必须这么写才能生效 并且没有向你这样排序，能发一下你的全部代码么

**Comment by jadestrong** [comment]
![image](https://github.com/user-attachments/assets/688b89d9-2bbb-4789-991e-2961d7dc3fb6)
我就是这么配的，你这是没有禁用lsp-mode吧，你把 doom-emacs 自带的 lsp 功能关掉，然后给你的 buffer 加到 lsp-copilot-mode-hook 里
![image](https://github.com/user-attachments/assets/606f113e-d409-481f-a041-ebae75860c74)

**Comment by TheEros** [comment]
可以了 点赞
